name: holtelmanagement
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.0.15
  flutter_switch: ^0.3.2
  intl: ^0.19.0
  swipeable_button_view: ^0.0.2
  just_audio: ^0.9.34
  flutter_secure_storage: ^9.2.2
  provider: ^6.0.5
  flutter_carousel_widget: ^2.2.0
  path_provider: ^2.1.5
  badges: ^3.0.0
  overlay_support: ^2.1.0
  logger: ^1.0.0
  flutter_rating_bar: ^4.0.1
  retry: ^3.1.2







dev_dependencies:
  flutter_gen: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/notification1.wav
    - assets/audio/specification1.mp3
    - assets/images/logo.png
    - lib/l10n/app_en.json
    - lib/l10n/app_no.json
    - lib/l10n/app_ar.json
    - lib/l10n/app_fr.json
    - assets/images/foods/food_services_slide_img-1.png
    - assets/images/foods/food_services_slide_img-2.png
    - assets/images/food_services_image.png
    - assets/images/request_services_image.png
    - assets/images/oderhistory.png


flutter_localizations:
  sdk: flutter
